### ISSUE TITLE
better sensor initialization/recover

### ISSUE THREAD

**Issue by fmirus** [ipa320/seneka_sensor_node#14]
the sensors are initialized randomly on the perimeter by now with random orientation. maybe this can be improved by placing the sensors in a "smarter" way.
another point is that if a sensor is moving out of the area of interest, the recovery behaviour can also be smarter (especially orientation).

**Comment by mgruhler** [comment]
Two ways I can think of:
1. Make them point add the midpoint of the polygon
2. Make them point perpendicular to the vertex on which it sits, facing inwards obviously

**Comment by fmirus** [comment]
a first draft was implemented. feedback and discussions are very welcome. further improvements are still possible.

**Comment by fmirus** [comment]
some improvements were achieved, but there is still potential for further improvement-ideas
