### ISSUE TITLE
make max velocity map dependent

### ISSUE THREAD

**Issue by mgruhler** [ipa320/seneka_sensor_node#26]
at the moment, we specify a max sensor velocity through parameters on the parameter server. as we are dealing with maps that might change considerably in size, this might highly restrict the possibilities for updates. 
(as seen on the big map just now)

maybe we should tie this to the size of the map rather than to specify them absolutely.

**Comment by fmirus** [comment]
good point. a possible way could be to find a reasonable correlation between the map size and a good choice for the maximal sensor velocity via parameter tests (see issue #27) and then tie these together like ipa-mig suggested.

**Comment by fmirus** [comment]
moved to https://github.com/ipa320/seneka_deployment_strategies/issues/9
