### ISSUE TITLE
implement an "adaptive"/random reinitialization

### ISSUE THREAD

**Issue by mgruhler** [ipa320/seneka_sensor_node#28]
just a wild thought...

maybe we could implement somthing similar to the error correction in particle filters. there, new particles are inserted based on a random function somewhere in the map.

we could tie this either to a random number as well (e.g. rand()<0.05) or to a minimal coverage. however, it should be only on a sensor basis.
reinitialization could be on perimeter or anywhere in the area.

if this is a performance improvement remains to be seen. also, this will make the algorithm even more undeterministic...

**Comment by fmirus** [comment]
a first draft was implemented in #39.

**Comment by fmirus** [comment]
moved to https://github.com/ipa320/seneka_deployment_strategies/issues/5
